export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
export const UNAUTHENTICATING_SUCCESS = "UNAUTHENTICATING_SUCCESS";

export const ADD_FLASH = "ADD_FLASH";
export const REMOVE_FLASH = "REMOVE_FLASH";
export const REMOVE_ALL_FLASH = "REMOVE_ALL_FLASH";

export const ADD_LOADING_ENTRY = "ADD_LOADING_ENTRY";
export const REMOVE_LOADING_ENTRY = "REMOVE_LOADING_ENTRY";

export const FETCH_ALL_BACKOFFICE_AGENTS_SUCCESS = "FETCH_ALL_BACKOFFICE_AGENTS_SUCCESS";
