export const AUTHENTICATING = "AUTHENTICATING";
export const UNAUTHENTICATING = "UNAUTHENTICATING";
export const SENDING_LOGIN_LINK = "SENDING_LOGIN_LINK";

export const FETCHING_PROFESSIONALS = "FETCHING_PROFESSIONALS";
export const FETCHING_EMPLOYERS = "FETCHING_EMPLOYERS";
export const CREATING_EMPLOYER = "CREATING_EMPLOYER";
export const FETCHING_SINGLE_EMPLOYER = "FETCHING_SINGLE_EMPLOYER";
export const INVITING_EMPLOYER_AGENT = "INVITING_EMPLOYER_AGENT";
